theme: jekyll-theme-cayman
title: JuliaGeo
description: ["JuliaGeo serves as a focal point for developing and maintaining the next generation of tooling for geospatial analysis in Julia."]
github:
  repository_url: ["https://github.com/JuliaGeo"]
  is_project_page: True
